
module.exports = [
    {short:"  " , name:"Seleccione su Estado"},
    {short:"AS" , name:"Aguascalientes"},
    {short:"BC" , name:"Baja California"},
    {short:"BS" , name:"Baja California Sur"},
    {short:"CC" , name:"Campeche"},
    {short:"CS" , name:"Chiapas"},
    {short:"CH" , name:"Chihuahua"},
    {short:"CL" , name:"Coahuila"},
    {short:"CM" , name:"Colima"},
    {short:"DF" , name:"Distrito Federal"},
    {short:"DG" , name:"Durango"},
    {short:"GT" , name:"Guanajuato"},
    {short:"GR" , name:"Guerrero"},
    {short:"HG" , name:"Hidalgo"},
    {short:"JC" , name:"Jalisco"},
    {short:"MC" , name:"Estado de México"},
    {short:"MN" , name:"Michoacán"},
    {short:"MS",  name:"Morelos"},
    {short:"NT",  name:"Nayarit"},
    {short:"NL" , name:"Nuevo León"},
    {short:"OC" , name:"Oaxaca"},
    {short:"PL" , name:"Puebla"},
    {short:"QT" , name:"Querétaro"},
    {short:"QR" , name:"Quintana Roo"},
    {short:"SP" , name:"San Luis Potosí"},
    {short:"SL" , name:"Sinaloa"},
    {short:"SR" , name:"Sonora"},
    {short:"TC" , name:"Tabasco"},
    {short:"TS" , name:"Tamaulipas"},
    {short:"TL" , name:"Tlaxcala"},
    {short:"VZ" , name:"Veracruz"},
    {short:"YN" , name:"Yucatán"},
    {short:"ZS" , name:"Zacatecas"}
]
  
